### ISSUE TITLE
Re-Deploy of SonarQube Yields Errors

### ISSUE THREAD

**Issue by dhongyt** [OpenShiftDemos/sonarqube-openshift-docker#10]
When I first deploy SonarQube + PostgreSQL using your sonarqube-postgresql-template, it deploys perfectly without any problems.

But when I re-deploy the sonarqube container a second time, I error out.

> 2018.05.25 19:11:42 INFO  app[][o.s.a.AppFileSystem] Cleaning or creating temp directory /opt/sonarqube/temp
2018.05.25 19:11:43 INFO  app[][o.s.a.es.EsSettings] Elasticsearch listening on /127.0.0.1:9001
2018.05.25 19:11:43 INFO  app[][o.s.a.p.ProcessLauncherImpl] Launch process[[key='es', ipcIndex=1, logFilenamePrefix=es]] from [/opt/sonarqube/elasticsearch]: /opt/sonarqube/elasticsearch/bin/elasticsearch -Epath.conf=/opt/sonarqube/temp/conf/es
2018.05.25 19:11:43 INFO  app[][o.s.a.SchedulerImpl] Waiting for Elasticsearch to be up and running
2018.05.25 19:11:45 INFO  app[][o.e.p.PluginsService] no modules loaded
2018.05.25 19:11:45 INFO  app[][o.e.p.PluginsService] loaded plugin [org.elasticsearch.transport.Netty4Plugin]
2018.05.25 19:11:53 WARN  app[][o.s.a.p.AbstractProcessMonitor] Process exited with exit value [es]: 1
2018.05.25 19:11:53 INFO  app[][o.s.a.SchedulerImpl] Process [es] is stopped
2018.05.25 19:11:53 INFO  app[][o.s.a.SchedulerImpl] SonarQube is stopped

From google search, this is saying I'm trying to run ElasticSearch as root. But I don't understand why its trying to run it as root the second time when the build should be running it as user sonar.

Any ideas on why this is happening?

My environment that I am testing this on is minishift.

**Comment by saikirandusari** [comment]
I see the same problem when deploying second time on OpenShift platform. First time deployment is always successful.

`2019.02.23 00:02:54 INFO  app[][o.s.a.AppFileSystem] Cleaning or creating temp directory /opt/sonarqube/temp
--
  | 2019.02.23 00:02:54 INFO  app[][o.s.a.es.EsSettings] Elasticsearch listening on /127.0.0.1:9001
  | 2019.02.23 00:02:54 INFO  app[][o.s.a.p.ProcessLauncherImpl] Launch process[[key='es', ipcIndex=1, logFilenamePrefix=es]] from [/opt/sonarqube/elasticsearch]: /opt/sonarqube/elasticsearch/bin/elasticsearch -Epath.conf=/opt/sonarqube/temp/conf/es
  | 2019.02.23 00:02:54 INFO  app[][o.s.a.SchedulerImpl] Waiting for Elasticsearch to be up and running
  | 2019.02.23 00:02:54 INFO  app[][o.e.p.PluginsService] no modules loaded
  | 2019.02.23 00:02:54 INFO  app[][o.e.p.PluginsService] loaded plugin [org.elasticsearch.transport.Netty4Plugin]
  | OpenJDK 64-Bit Server VM warning: If the number of processors is expected to increase from one, then you should configure the number of parallel GC threads appropriately using -XX:ParallelGCThreads=N
  | 2019.02.23 00:04:19 INFO  app[][o.s.a.SchedulerImpl] Stopping SonarQube
  | 2019.02.23 00:04:19 ERROR app[][o.s.a.p.EsProcessMonitor] Failed to check status
  | java.lang.IllegalStateException: ClusterService was close during health call
  | at org.elasticsearch.action.admin.cluster.health.TransportClusterHealthAction$3.onClusterServiceClose(TransportClusterHealthAction.java:180)
  | at org.elasticsearch.cluster.ClusterStateObserver$ContextPreservingListener.onClusterServiceClose(ClusterStateObserver.java:304)
  | at org.elasticsearch.cluster.ClusterStateObserver$ObserverClusterStateListener.onClose(ClusterStateObserver.java:224)
  | at org.elasticsearch.cluster.service.ClusterService.doStop(ClusterService.java:230)
  | at org.elasticsearch.common.component.AbstractLifecycleComponent.stop(AbstractLifecycleComponent.java:88)
  | at org.elasticsearch.node.Node.stop(Node.java:787)
  | at org.elasticsearch.node.Node.close(Node.java:809)
  | at org.apache.lucene.util.IOUtils.close(IOUtils.java:89)
  | at org.apache.lucene.util.IOUtils.close(IOUtils.java:76)
  | at org.elasticsearch.bootstrap.Bootstrap$4.run(Bootstrap.java:209)
  | 2019.02.23 00:04:21 WARN  app[][o.s.a.p.AbstractProcessMonitor] Process exited with exit value [es]: 143
  | 2019.02.23 00:04:21 INFO  app[][o.s.a.SchedulerImpl] Process [es] is stopped
  | 2019.02.23 00:04:21 INFO  app[][o.s.a.SchedulerImpl] SonarQube is stopped`
