### ISSUE TITLE
Sonarqube startup problem

### ISSUE THREAD

**Issue by deepjyotsingh** [OpenShiftDemos/sonarqube-openshift-docker#8]
Looks like the /opt/sonarqube/data volume is owned by root which is preventing the services to start.

![image](https://user-images.githubusercontent.com/37116675/37456176-c443b6ca-2864-11e8-803d-7815ef404870.png)

java.lang.IllegalStateException: Failed to created node environment
        at org.elasticsearch.node.Node.<init>(Node.java:167)
        at org.elasticsearch.node.Node.<init>(Node.java:140)
        at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:143)
        at org.sonar.search.SearchServer.start(SearchServer.java:62)
        at org.sonar.process.ProcessEntryPoint.launch(ProcessEntryPoint.java:111)
        at org.sonar.process.ProcessEntryPoint.launch(ProcessEntryPoint.java:98)
        at org.sonar.search.SearchServer.main(SearchServer.java:109)
**Caused by: java.nio.file.AccessDeniedException: /opt/sonarqube/data/es**
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384)
        at java.nio.file.Files.createDirectory(Files.java:674)
        at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781)
        at java.nio.file.Files.createDirectories(Files.java:767)
        at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:169)
        at org.elasticsearch.node.Node.<init>(Node.java:165)
        ... 6 common frames omitted

**Comment by deepjyotsingh** [comment]
I have used the below template to create the persistent volume...

![image](https://user-images.githubusercontent.com/37116675/37456699-0375af78-2866-11e8-8400-bc28550b1990.png)

**Comment by bsk01** [comment]
Same here. Start up issue in openshift.

2018.04.19 01:05:51 INFO  app[][o.s.a.AppFileSystem] Cleaning or creating temp directory /opt/sonarqube/temp
--
  | 2018.04.19 01:05:51 INFO  app[][o.s.a.es.EsSettings] Elasticsearch listening on /127.0.0.1:9001
  | 2018.04.19 01:05:52 INFO  app[][o.s.a.p.ProcessLauncherImpl] Launch process[[key='es', ipcIndex=1, logFilenamePrefix=es]] from [/opt/sonarqube/elasticsearch]: /opt/sonarqube/elasticsearch/bin/elasticsearch -Epath.conf=/opt/sonarqube/temp/conf/es
  | 2018.04.19 01:05:52 INFO  app[][o.s.a.SchedulerImpl] Waiting for Elasticsearch to be up and running
  | 2018.04.19 01:05:53 INFO  app[][o.e.p.PluginsService] no modules loaded
  | 2018.04.19 01:05:53 INFO  app[][o.e.p.PluginsService] loaded plugin [org.elasticsearch.transport.Netty4Plugin]
  | 2018.04.19 01:05:59 WARN  app[][o.s.a.p.AbstractProcessMonitor] Process exited with exit value [es]: 1
  | 2018.04.19 01:05:59 INFO  app[][o.s.a.SchedulerImpl] Process [es] is stopped
  | 2018.04.19 01:05:59 INFO  app[][o.s.a.SchedulerImpl] SonarQube is stopped

**Comment by agvikashsagar** [comment]
Any workaround for this issue, facing the same in SonarQube 7.0
